name: Test

on:
  - push
  - pull_request

jobs:
  flake:
    name: Run flake checks
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v29

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: test-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: test-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: test-${{ runner.os }}-
          purge-created: 60
          purge-primary-key: never

      - name: Run tests
        run: |
          nix --print-build-logs --experimental-features 'nix-command flakes' flake check

  go:
    name: Run Go tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.3'

      - name: Go generate
        run: >-
          go generate ./...

      - name: Run tests
        run: >-
          go test ./...

      - name: Build for test
        id: build-test
        run: >-
          HIZLA_VERSION="$(git rev-parse --short HEAD)"
          bash -c './dist/release.sh &&
          echo "rev=$HIZLA_VERSION" >> $GITHUB_OUTPUT'

      - name: Upload test build
        uses: actions/upload-artifact@v4
        with:
          name: "hizla-${{ steps.build-test.outputs.rev }}"
          path: dist/hizla-*
          retention-days: 1
